### ISSUE TITLE
Titlovi.com issue

### ISSUE THREAD

**Issue by markcwee** [mikimac/service.subtitles.titlovi#2]
after updating titlovi.com website, api changed, this addon doesn't work anymore in any of Kodi versions. Fix?

**Comment by matko238** [comment]
No API yet, addon needs extensive changes in parser (new DOM parser) in order to work.

**Comment by mikimac** [comment]
I'm working on solution to resolve problem with API.

**Comment by brdardusan** [comment]
Please let us know when changes R complet.

**Comment by rule111** [comment]
Hello, problem with subtitles is still with TV series, when searching it is endless , for movies it works, also manual search does not find subs, I've tried different tv shows

**Comment by xalexas** [comment]
Hello, subtitles from Titlovi.com doesn't work. I guess titlovi.com has changed website again.

**Comment by alipasijaner** [comment]
Hello there, this is great plugin for kodi but does not working anymore with website titlovi.com :( keep up the good work 
Best regards

**Comment by horvat1** [comment]
Hello, subtitles from Titlovi.com doesn't work. I guess titlovi.com has changed website again.
Please help again
Best regards

**Comment by mikimac** [comment]
I have solved problem and soon will be updated new version with corrections.
